# --- Explanation --- #
# UniqueID:
#     # These children are possible options for children, all will be taken.
#     children: [Child1, Child2]
#
#     # Indirect children which *have to* follow this node at some point, otherwise the classification is invalid.
#     descendants: [Descendant1, Descendant2]
#
#     # Whenever specified to be True the classification will not try all possibilities of children, but
#     # instead it will take the best option and stick with it. Use this with the first couple of splits
#     # to greatly reduce search space.
#     take_best: True
#
#     # Use children on the first few nodes where the structure is meant to be stable, then stick to optional_children
#     # and guarantee that some children appear at some point by using descendants

# --- Reference --- #
# https://i.pinimg.com/originals/eb/e1/6f/ebe16f5cffc897873071d0cde7640c5d.png

Trachea:
    children: [Bronchus]
    take_best: True
    # color: cadeca
    color: ffffff
Bronchus:
    children: [LBronchus, RBronchus]
    vector: [176.0, 53.0, -9.0]
    take_best: True




# --- Left Bronchus --- #
LBronchus:
    children: [LUpperLobe, LLowerLobe]
    descendants: [LUpperLobe, LLowerLobe, Lingular]
    vector: [70.5, 8.0, 60.0]
    take_best: True

# --- Left upper lobe --- #
LUpperLobe:
    children: [Lingular, LB1+2+3, LB1+2, LB3]
    descendants: [LB1, LB2, LB3]
    vector: [-15.5, -9.0, 22.5]
    # take_best: True
Lingular:
    children: [LB4, LB5]
    vector: [23.5, -19.0, 16.5]
LB1+2+3:
    children: [LB1+2, LB1, LB2, LB3]
    descendants: [LB1, LB2, LB3]
    vector: [-15.0, -2.0, 4.0]
LB1+2:
    children: [LB1, LB2]
    descendants: [LB1, LB2]
    vector: [-21.0, 3.0, 1.0]
    color: ff3432
LB3:
    children: [LB3a, LB3b, LB3c]
    vector: [-4.0, -7.0, 10.0]
    color: 6FB0FF
LB1:
    vector: [-40.0, 8.5, -5.0]
    color: ff3432
LB2:
    vector: [-20.0, -17.0, 3.0]
    color: ff3432
LB4:
    color: f6c460
    vector: [-23.0, -5.0, -11.5]
LB5:
    color: ff6822
    vector: [-4.0, 0.0, -13.0]

# --- Left lower lobe --- #

LLowerLobe:
    vector: [19.0, 8.5, 13.5]
    children: [LB6, LB7+8+9+10]
LB6:
    vector: [-1.0, 10.5, 3.5]
    color: c44b98
LB7+8+9+10:
    vector: [35.5, -2.0, 13.5]
    children: [LB7+8, LB9+10, LB9, LB10]
    # children: [LB7+8, LB7, LB8, LB9+10, LB9, LB10] # doesn't work correctly
    descendants: [LB7+8, LB9, LB10]
LB9+10:
    vector: [12.0, 3.5, 2.5]
    children: [LB9, LB10]
LB7+8:
    vector: [10.0, -4.0, 19.0]
    children: [LB7, LB8]
    color: ffc200
LB9:
    vector: [31.0, -2.5, 16.0]
    color: bc6a26
LB10:
    vector: [34.66, 10.0, 8.66]
    color: e74a00
LB7:
    vector: [10.0, -6.5, 10.0]
    color: ffc200
LB8:
    vector: [10.0, -6.5, 10.0]
    color: ffc200

# --- Right Bronchus --- #
RBronchus:
    children: [RUpperLobe, RMLLobes]
    vector: [28.5, 5.0, -23.0]
    take_best: True

RUpperLobe:
    vector: [-13.5, -1.0, -18.0]
    children: [RB1, RB2, RB3]

RMLLobes:
    children: [RMiddleLobe, RLowerLobe, RB6]
    vector: [46.5, 10.0, -9.0]

# RMiddleLobe:
#     vector: [17.5, -21.5, -13.5]
#     children: [RB4, RB5]
#
# RLowerLobe:
#     vector: [34.0, 2.0, -7.5]
#     children: [RB7, RB8, RB9, RB10]
#
# RB6:
#     vector: [8.0, 15.0, -12.0]
#     color: c44b98
