# Path can be a path directly to your data path
# where all stages will be located
path: /path/to/data

# Alternatiely this notation is supported as well:
# 
# path: local
# paths:
    # local: /path/to/local_data/
    # remote: /path/to/remote_data/
#
# Here paths is a keyword which has to be in paths,
# this allows easy use of multiple paths by using
# the -P flag in either script to specify
#
# ./airway-pipeline.py -P remote 
# or
# ./airway-vis.py -P remote 
#
# when you want to work on the remote data path
# without having to write out the entire path.
# Uncomment inf needed and remove the path
# at the top of the file.

workers: 4
force: True
single: False
